### ISSUE TITLE
Tanstack Router Error When Running Example

### ISSUE THREAD

**Issue by drew-harris** [marbemac/ssrx#32]
When cloning the repo, yarn installing, and running `yarn nx run tanstack-router-simple:dev`. The following error happens when opening the page:

```
Error while rendering the app shell TypeError: Cannot read properties of undefined (reading 'filter')
    at Meta (file:///Users/drew/clones/ssrx/node_modules/@tanstack/react-router-server/dist/esm/client.js:97:83)
    at renderWithHooks (/Users/drew/clones/ssrx/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/drew/clones/ssrx/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/drew/clones/ssrx/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/drew/clones/ssrx/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/drew/clones/ssrx/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/drew/clones/ssrx/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/drew/clones/ssrx/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/drew/clones/ssrx/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/drew/clones/ssrx/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
TypeError: Cannot read properties of undefined (reading 'filter')
```
(Error happens multiple times in quick succession)

This happens both for the dev script and also when building and starting. (The build process is successful though)

Using node version: v20.13.0, and yarn version 4.0.2. 
Please let me know if you need any more info. I will keep investigating but I am unfamiliar to the repo and how everything works.

**Comment by drew-harris** [comment]
Update: Removing the <Meta /> tag, imported from `@tanstack/react-router-server` on line 25 fixes the error. Not sure of the ramifications however but things seem to be working fine on first impression.

**Comment by marbemac** [comment]
Hi @drew-harris - taking a look today, will let ya know.

**Comment by marbemac** [comment]
Alrighty, updated main to latest version of tanstack-router and tidied up accordingly. Seems like there are still some issues with tanstack router + SSR, but I don't believe they are ssrx specific (meta tags like title etc don't seem to be working in tanstack's own examples, and the issue mentioned here -> https://github.com/marbemac/ssrx/blob/main/examples/tanstack-router-simple/src/entry.client.tsx#L12-L14).

LMK if all seems in order now!

**Comment by drew-harris** [comment]
Just recloned, and the example works just fine now (minus the meta tags like you pointed out, which I don't need for my use cases)

Thank you so much!
